/*drop database TESTMEZUBO;*/
CREATE DATABASE TESTMEZUBO;

USE TESTMEZUBO;

CREATE TABLE ROULETTE (
    ROULETTE_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    OPENING BOOLEAN,
    WINNERNUMBER INT,
    WINNERCOLOR BOOLEAN
);

CREATE TABLE BET (
	BET_ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ROULETTE_ID INT NOT NULL,
    BETNUMBER INT,
    BETCOLOR BOOLEAN,
    AMOUNTMONEY SMALLINT,
    FOREIGN KEY (ROULETTE_ID) REFERENCES ROULETTE (ROULETTE_ID)
);

INSERT INTO ROULETTE (OPENING) VALUES (false);
SELECT LAST_INSERT_ID();
select * from ROULETTE;
update ROULETTE set OPENING = false where ROULETTE_ID = '5';
select * from BET;
SELECT BETNUMBER, BETCOLOR, AMOUNTMONEY, ROULETTE_ID FROM BET
                        WHERE ROULETTE_ID = '58';
                        
INSERT INTO BET (ROULETTE_ID, BETNUMBER, BETCOLOR, AMOUNTMONEY) VALUES (58, 23, 1, 3000);

select BET.ROULETTE_ID,
	BET.BETNUMBER, 
    BET.BETCOLOR,
    BET.AMOUNTMONEY, 
    ROULETTE.WINNERNUMBER,
    ROULETTE.WINNERCOLOR 
    from BET,ROULETTE where BET.ROULETTE_ID = ROULETTE.ROULETTE_ID;